name: .NET CI/CD on Windows Server 2019

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  build:
    runs-on: windows-2019  # Use Windows Server 2019 to build the application

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Get your code from the repository

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish  # Prepare app for deployment

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-publish
          path: ./publish  # Upload the build output as an artifact

  deploy:
    runs-on: windows-2019  # Use Windows Server 2019 to deploy the application
    needs: build  # Ensure deployment only happens after a successful build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-publish  # Download the artifact from the build job

      - name: Deploy to Windows Server 2019 via SSH
        uses: appleboy/ssh-action@v0.1.0  # SSH action for deploying to the server
        with:
          host: ${{ secrets.WINDOWS_SERVER_IP }}  # The IP of your server
          username: ${{ secrets.WINDOWS_SERVER_USER }}  # SSH username (Administrator)
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}  # SSH password
          port: 22  # Default SSH port
          source: './publish/*'  # Files to transfer to the server
          target: 'C:/inetpub/wwwroot/yourapp'  # Target directory on your server where IIS serves the app

      - name: Restart IIS (optional)
        run: |
          iisreset  # Restart IIS to load the new deployment
